[build]
  base = ""
  publish = "dist"
  command = "npm run build"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

[dev]
  framework = "#custom"
  command = "npm run dev"
  port = 8888
  targetPort = 5000
  publish = "dist"
  autoLaunch = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
